[tool.poetry]
name = "pathpilot"
version = "0.1.3"
description = "Library that facilitates file and folder manipulation in Python."
authors = ["Zachary Einck <zacharyeinck@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/zteinck/pathpilot"
homepage = "https://github.com/zteinck/pathpilot"

[tool.poetry.dependencies]
python = "^3.8"
iterlab = "*"
clockwork = "*"
pandas = "*"
numpy = "*"
XlsxWriter = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"